/**
 * Augments the ambient CloudflareEnv interface with runtime bindings that are
 * intentionally not hand-written into cloudflare-env.d.ts. That file is
 * regenerated by `npm run cf-typegen`, while these declarations must survive
 * regeneration.
 */
declare global {
  interface CloudflareEnv {
    /**
     * D1 database used by the anonymous visitor counter. Cloudflare build
     * settings provide the binding; its ID is not committed to the repository.
     */
    VISITOR_DB?: D1Database;
  }
}

export {};
